#!/bin/bash

if [ "$1" == "debug" ]; then
	name="python proxy\.py debug"
else
	name="python proxy\.py"
fi

{ ps aux | grep "$name" | grep -v grep | awk '{print $2}' | xargs kill 2>/dev/null ; } &&
	echo "Killed proxy"
